-- APAGAR A TABELA PARA TESTES
DROP TABLE T_TESTE_DDL_SEQUENCE;

-- CRIAR UMA TABELA PARA TESTES
CREATE TABLE T_TESTE_DDL_SEQUENCE
(
CD_TESTE_SQ NUMBER(3) NOT NULL ,
NM_TESTE_SQ VARCHAR2(30) NOT NULL
);

-- ADICIONAR A CONSTRAINT CHAVE PRIMARIA
ALTER TABLE T_TESTE_DDL_SEQUENCE
ADD CONSTRAINT PK_TESTE_DDL_SEQUENCE
PRIMARY KEY (CD_TESTE_SQ);

-- CRIAR SEQUENCIA PARA GERAR UM CODIGO AUTO NUMERICO 
CREATE SEQUENCE SQ_TESTE_DDL_SEQUENCE
    START WITH 1    -- PRIMEIRO NUMERO A SER GERADO (VALOR INICIAL DA SEQUENCIA)
  INCREMENT BY 1    -- VALOR DO INCREMENTO (DIFERENTE DE ZERO)
      MAXVALUE 999  -- MAIOR VALOR DA SEUENCIA 999 (CAMPO CHAVE PRIMARIA CD_TESTE_SQ NUMBER(3) - O QUE CABE EM UM NUMBER(3) -> 999
      NOCACHE       -- SEM CACHE (NÃO SERÃO CRIADOS NUMEROS PREVIAMENTE E DEIXADOS NA MEMORIA - OS VALORES SERÃO CRIADOS NO MOMENTO QUE SOLICITAR A SEQUENCIA)
      NOCYCLE;      -- NAO REINICIA A SEQUENCIA


-- UTILIZAR SEQUENCIA EM UMA INSERÇAO
INSERT INTO T_TESTE_DDL_SEQUENCE VALUES (SQ_TESTE_DDL_SEQUENCE.NEXTVAL, 'TESTE'); 
-- NEXTVAL -> GERA O PROXIMO NUMERO DA SEQUENCIA
SELECT * FROM T_TESTE_DDL_SEQUENCE;

-- CONSULTANDO O VALOR CORRENTE DE UMA SEQUENCIA
SELECT SQ_TESTE_DDL_SEQUENCE.CURRVAL FROM DUAL;
-- CURRVAL -> RECUPERA O VALOR CORRENTE DA SEQUENCIA

/*
DUAL -> É uma tabela do sistema ORACLE, pertence ao usuário SYS, utilizado por desenvolvedores,
DBA e pela própria ORACLE, quando é necessário realizar uma consulta (operação SELECT),
onde não é necessário extrair dados de uma tabela. Não pode ser excluída.
Possui apenas uma coluna, nomeada “DUMMY” do tipo VARCHAR2(1) com o conteúdo “X”.
*/

-- ESTRUTURA DA DUAL 
DESC DUAL;

-- CONSULTAR A DUAL
SELECT * FROM DUAL;

-- CONSULTAR DATA DOS SISTEMA
SELECT SYSDATE FROM DUAL;

-- CONSULTANDO UMA SEQUENCE NA TABELA DE SEQUENCIAS DO ORACLE 
SELECT SEQUENCE_NAME, INCREMENT_BY, MAX_VALUE, LAST_NUMBER
  FROM USER_SEQUENCES
 WHERE SEQUENCE_NAME = 'SQ_TESTE_DDL_SEQUENCE';
 
-- PROVOCAR UM GAP (INTERVALO) NA SEQUENCIA
SELECT SQ_TESTE_DDL_SEQUENCE.NEXTVAL FROM DUAL;

/*
Limitações e observações para alteração de uma sequência:
O valor inicial de uma sequência não pode ser alterado.
O valor mínimo não pode ser maior que o valor atual da sequência.
O valor máximo não pode ser menor do que o valor atual da sequência.
Para alterar uma sequência é necessário ser proprietário dela.
Somente os números futuros da sequência são afetados após a alteração.
A sequência deve ser eliminada e recriada para que seja reiniciada em um número diferente.
*/

-- ALTERANDO UMA SEQUENCIA 
ALTER SEQUENCE SQ_TESTE_DDL_SEQUENCE
  INCREMENT BY 5
      MAXVALUE 900;
      
-- PARA ELIMINAR A SEQUENCIA 
DROP SEQUENCE SQ_TESTE_DDL_SEQUENCE;







