-- COMANDOS SQL - DIVISÃO: DQL / DRS
-- DQL (Data Query Language) -> LINGUAGEM DE CONSULTA DE DADOS
-- DRS (Data Retrieve Language ) -> LINGUAGEM DE RECUPERAÇÃO DE DADOS
-- Aula17_TBD_DMSQL_DRS_OPERADORES_EXPRESSOES_RitaCRodrigues.PDF

-- ALGUNS AUTORES TRATAM COMO DML - Data Manipulation Language);


-- COMANDO: SELECT -> COMANDO PARA CONSULTA/RECUPERAÇÃO DE DADOS

-- NESTE MATERIAL IREMOS TRATAR DE CONSULTA SIMPLES (CONSULTA A APENAS UMA TEBELA)

-- CONSULTADO TODAS AS LINHAS E COLUNAS DA TABELA FUNCIONARIO
SELECT * FROM T_SIP_FUNCIONARIO;
-- SELECT -> CONSULTA
-- * -> REPRESENTA TODAS AS COLUNAS DA TABELA
-- FROM -> CLAUSULA QUE INDICA AS TABELAS A SEREM CONSULTADAS
-- T_SIP_FUNCIONARIO -> TABELA A SER CONSULTADA


-- Especificando as colunas que deseja consultar e recuperando todas as linhas da tabela FUNCIONARIO
SELECT nr_matricula, nm_funcionario, vl_salario_mensal
  FROM T_SIP_FUNCIONARIO; -- TABELA A SER CONSULTADA
  
-- Especificando as colunas que deseja consultar e filtrando as linhas da tabela FUNCIONARIO.
SELECT cd_depto, nr_matricula, nm_funcionario, vl_salario_mensal
  FROM T_SIP_FUNCIONARIO
 WHERE cd_depto = 3;

/*
Dê preferencia a consultas onde as colunas e filtro são especificados, com isso evitamos  
retornar informações que não serão utilizadas pelo usuário.
*/

-- RECUPERANDO OS DEPARTAMENTOS (SEM REPETIÇÃO) QUE POSSUEM FUNCIONARIOS.
-- QUAIS DEPARTAMENTOS POSSUEM FUNCIONARIOS TRABALHANDO ?
SELECT DISTINCT cd_depto FROM T_SIP_FUNCIONARIO;
-- OU
SELECT UNIQUE cd_depto FROM T_SIP_FUNCIONARIO;

-- VIZUALIZANDO TODOS OS DEPTOS ASSOCIADOS AOS FUNCIONARIOS
SELECT cd_depto FROM T_SIP_FUNCIONARIO;

-- QUAIS PROJETOS ESTÃO EM IMPLANTAÇÃO ?
SELECT DISTINCT cd_projeto FROM T_SIP_IMPLANTACAO;
-- OU
SELECT UNIQUE cd_projeto FROM T_SIP_IMPLANTACAO;

-- QUAIS FUNCIONARIOS POSSUEM DEPENDENTES ?
SELECT DISTINCT nr_matricula FROM T_SIP_DEPENDENTE;
-- OU
SELECT UNIQUE nr_matricula FROM T_SIP_DEPENDENTE;


-- Exemplo de consulta utilizando operadores aritméticos
-- RECUPERAR OS FUNCIONARIOS, APLICANDO 5% DE AUMENTO NO SALARIO 
SELECT nr_matricula, nm_funcionario, vl_salario_mensal * 1.05 
  FROM T_SIP_FUNCIONARIO;
  
-- EXEMPLO DE CONSULTA CALCULANDO COMISSÃO DE AUMENTO
SELECT nr_matricula, nm_funcionario, (vl_salario_mensal + 120) * 1.10 
  FROM T_SIP_FUNCIONARIO;
  
-- APELIDOS (ALIAS) DE COLUNAS 
SELECT nr_matricula, nm_funcionario, vl_salario_mensal * 1.05 AS "VALOR AJUSTADO"
  FROM T_SIP_FUNCIONARIO;

-- AS É OPCIONAL
SELECT nr_matricula, nm_funcionario, vl_salario_mensal * 1.05 "VALOR AJUSTADO"
  FROM T_SIP_FUNCIONARIO;

-- ASPAS DUPLAS, SAO REQUERIDAS PARA NOMES COMPOSTOS 
SELECT nr_matricula, nm_funcionario, vl_salario_mensal * 1.05 VALOR
  FROM T_SIP_FUNCIONARIO;
  
-- APRESENTANDO RESULTADOS DE FORMA ORDENADA
-- ORDER BY ASC (ASCENDENTE/CRESCENTE)
  SELECT cd_depto, nm_depto
    FROM T_SIP_DEPTO
ORDER BY nm_depto;

-- ORDER BY DESC (ASCENDENTE/CRESCENTE)
  SELECT cd_depto, nm_depto
    FROM T_SIP_DEPTO
ORDER BY nm_depto DESC;

-- ORDER BY ASC E DESC E UTILIZANDO MAIS DE UMA COLUNA
  SELECT NR_MATRICULA, CD_DEPTO, NM_FUNCIONARIO, VL_SALARIO_MENSAL
    FROM T_SIP_FUNCIONARIO
   WHERE CD_DEPTO > 1
ORDER BY CD_DEPTO ASC, NM_FUNCIONARIO DESC;

-- ORDER BY UTILIZANDO NÚMEROS QUE REPRESENTAM AS COLUNAS
  SELECT NR_MATRICULA, CD_DEPTO, NM_FUNCIONARIO, VL_SALARIO_MENSAL
    FROM T_SIP_FUNCIONARIO
   WHERE CD_DEPTO > 1
ORDER BY 2 ASC, 3 DESC;

-- ORDER BY UTILIZANDO O APELIDO DAS COLUNAS
  SELECT NR_MATRICULA          "MATRÍCULA",
         NM_FUNCIONARIO             "NOME",
         VL_SALARIO_MENSAL "SALÁRIO MENSAL"
    FROM T_SIP_FUNCIONARIO
ORDER BY "SALÁRIO MENSAL" DESC;

-- FILTRANDO POR NÚMEROS
SELECT NR_MATRICULA, CD_DEPTO, NM_FUNCIONARIO, VL_SALARIO_MENSAL
    FROM T_SIP_FUNCIONARIO
   WHERE VL_SALARIO_MENSAL > 1500.50;

-- FILTRANTO POR TEXTO
SELECT NR_MATRICULA, NM_FUNCIONARIO
    FROM T_SIP_FUNCIONARIO
   WHERE UPPER(NM_FUNCIONARIO) = 'JOAO DA SILVA';

-- OU

SELECT NR_MATRICULA, NM_FUNCIONARIO
    FROM T_SIP_FUNCIONARIO
   WHERE LOWER(NM_FUNCIONARIO) = 'joao da silva';

-- FILTRANDO POR DATA 
SELECT NR_MATRICULA, NM_FUNCIONARIO, DT_ADMISSAO, CD_DEPTO
    FROM T_SIP_FUNCIONARIO
   WHERE DT_ADMISSAO > TO_DATE('01/08/2015', 'DD/MM/YYYY') AND CD_DEPTO = 3;

-- OPERADOR OR 
  SELECT NR_MATRICULA, NM_FUNCIONARIO, DT_ADMISSAO, CD_DEPTO
    FROM T_SIP_FUNCIONARIO
   WHERE CD_DEPTO = 4 OR VL_SALARIO_MENSAL > 3000;

-- EXEMPLOS utilizando operadores ESPECIAIS
-- OPERADOR BETWEEN
-- RECUPERAR OS FUNCIONARIOS QUE GANHAM ENTRE 1000 E 2500 (INCLUSIVE)
-- SALARIO >= 1000 AND SALARIO <= 2500 (BETWEEN)
-- SALARIO > 1000 AND SALARIO <= 2500 (NÃO PODE USAR BETWEEN)
-- SALARIO >= 1000 AND SALARIO < 2500 (NÃO PODE USAR BETWEEN)
-- SALARIO > 1000 AND SALARIO < 2500 (NÃO PODE USAR BETWEEN)
SELECT NR_MATRICULA, NM_FUNCIONARIO, CD_DEPTO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO
 WHERE VL_SALARIO_MENSAL BETWEEN 1000 AND 2500;

SELECT NR_MATRICULA, NM_FUNCIONARIO, CD_DEPTO, DT_ADMISSAO
  FROM T_SIP_FUNCIONARIO
 WHERE DT_ADMISSAO BETWEEN TO_DATE('01/01/2013', 'DD/MM/YYYY') AND TO_DATE('30/12/2015', 'DD/MM/YYYY');


-- OPERADOR IN (AVALIA LISTA DE VALORES )
SELECT NR_MATRICULA, NM_FUNCIONARIO, CD_DEPTO
  FROM T_SIP_FUNCIONARIO
 WHERE CD_DEPTO IN (1,2,3);
-- CD_DEPTO IN (1,2,3) EQUIVALE
-- CD_DEPTO = 1 OR CD_DEPTO = 2 OR CD_DEPTO = 3

-- OPERADOR NOT IN 
SELECT NR_MATRICULA, NM_FUNCIONARIO, CD_DEPTO
  FROM T_SIP_FUNCIONARIO
 WHERE CD_DEPTO NOT IN (1,2,3);
-- CD_DEPTO NOT IN (1,2,3) EQUIVALE
-- CD_DEPTO <> 1 AND CD_DEPTO <> 2 AND CD_DEPTO <> 3


-- OPERADOR IN
SELECT NR_MATRICULA, DT_ADMISSAO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO
 WHERE TO_CHAR(DT_ADMISSAO, 'YYYY') IN ('2012', '2014');



-- TO_CHAR() -> CONVERTE UM CONTEUDO PARA TEXTO
-- TO_CHAR(DT_ADMISSAO, 'YYYY') -- EXTRAIR O ANO DA DATA PARA CARACTERES
-- SE O ANO DA DATA ADMISSAO É 2012 OU 2014-- WHERE TO_CHAR(DT_ADMISSAO, 'YYYY') IN ('2012','2014')
-- EQUIVALE:
/*
DT_ADMISSAO BETWEEN TO_DATE('01/01/2012','DD/MM/YYYY') AND
TO_DATE('31/12/2012','DD/MM/YYYY') AND
DT_ADMISSAO BETWEEN TO_DATE('01/01/2014','DD/MM/YYYY') AND
TO_DATE('31/12/2014','DD/MM/YYYY')
*/
/*
DT_ADMISSAO >= TO_DATE('01/01/2012','DD/MM/YYYY') AND
DT_ADMISSAO <= TO_DATE('31/12/2012','DD/MM/YYYY') AND
DT_ADMISSAO >= TO_DATE('01/01/2014','DD/MM/YYYY') AND
DT_ADMISSAO <= TO_DATE('31/12/2014','DD/MM/YYYY')
*/

/*
DT_ADMISSAO BETWEEN TO_DATE('01/01/2012','DD/MM/YYYY') AND
TO_DATE('31/12/2012','DD/MM/YYYY') OR
DT_ADMISSAO BETWEEN TO_DATE('01/01/2014','DD/MM/YYYY') AND
TO_DATE('31/12/2014','DD/MM/YYYY')
*/
/*
DT_ADMISSAO >= TO_DATE('01/01/2012','DD/MM/YYYY') AND
DT_ADMISSAO <= TO_DATE('31/12/2012','DD/MM/YYYY') OR
DT_ADMISSAO >= TO_DATE('01/01/2014','DD/MM/YYYY') AND
DT_ADMISSAO <= TO_DATE('31/12/2014','DD/MM/YYYY')
*/


-- OPERADOR IS NOT NULL
SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO
FROM T_SIP_PROJETO
WHERE DT_TERMINO IS NOT NULL;


-- OPERADOR IS NULL 
SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO
FROM T_SIP_PROJETO
WHERE DT_TERMINO IS NULL;


-- OPERADOR LIKE (RECUPERA AS CORRESPONDENCIAS: EX, TUDO QUE COMEÇA COM A LETRA "A", TODOS OS NOMES QUE
-- CONTEM "SILVA"
SELECT CD_DEPTO, NM_DEPTO
FROM T_SIP_DEPTO
WHERE NM_DEPTO LIKE 'FIN%';

SELECT NR_MATRICULA, NM_FUNCIONARIO
FROM T_SIP_FUNCIONARIO
WHERE NM_FUNCIONARIO LIKE '%SILVA%';

-- % -> EQUIVALE A UMA CADEIA DE CARACTERES
-- _ -> EQUIVALE A APENAS UM CARACTER 
SELECT CD_DEPTO, NM_DEPTO
FROM T_SIP_DEPTO
WHERE NM_DEPTO LIKE '_A%';

SELECT CD_DEPTO, NM_DEPTO
FROM T_SIP_DEPTO
WHERE NM_DEPTO LIKE '___UR%';


-- EXIBIR O TEXTO: : "O FUNCIONMARIO <NOME> FOI ADIMITIDO EM <DATA EMISSAO>"
SELECT NR_MATRICULA, 'O FUNCIONARIO ' || NM_FUNCIONARIO || ', FOI ADMITIDO EM: ' || DT_ADMISSAO "TEXTO"
  FROM T_SIP_FUNCIONARIO;


-- UTILIZANDO A PSEUDOCOLUNA ROWNUM
SELECT ROWNUM, CD_DEPTO, NM_DEPTO
  FROM T_SIP_DEPTO;
  
-- RESTRINGINDO A QUANTIDADE DE LINHAS RECUPERADAS DURANTE A CONSULTA
  SELECT NR_MATRICULA, NM_FUNCIONARIO, DT_ADMISSAO, VL_SALARIO_MENSAL, VL_SALARIO_MENSAL * 12 "SALARIO ANUAL"
    FROM T_SIP_FUNCIONARIO
   WHERE ROWNUM <= 5
ORDER BY "SALARIO ANUAL" DESC;

-- PARA EXIBIR OS NOMES E OS SALÁRIOS DOS TRÊS FUNCIONÁRIOS
-- MAIS BEM REMUNERADOS DA TABELA FUNCIONARIO.
SELECT ROWNUM AS RANK,
       NM_FUNCIONARIO,
     VL_SALARIO_MENSAL
FROM (SELECT NM_FUNCIONARIO, VL_SALARIO_MENSAL FROM T_SIP_FUNCIONARIO ORDER BY VL_SALARIO_MENSAL DESC)
WHERE ROWNUM <= 3;

-- PARA ALTERAR O FORMATO DE EXIBICAO É UTILIZADO A SINTAXE:
-- ALTER SESSION SET NLS_DATE_FORMAT = FORMATO_DATA;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH:MI';

-- RECUPERAÇÃO DE DATA USANDO TO_CHAR() E APONTANDO PARA A TABELA DUAL
SELECT SYSDATE,
       TO_CHAR (SYSDATE, 'MON') "MES ABREVIADO",
       TO_CHAR (SYSDATE, 'MONTH') "MES ABREVIADO"
    FROM DUAL;
       

DESC DUAL;

SELECT * FROM DUAL;

-- TABELAS PRÓPRIAS DO ORACLE

