-- VEREMOS UM POUCO MAIS DE COMANDOS DDL (LINGUAGEM DE DEFINIÇÃO DE DADOS)
-- ONDE TRABALHAREMOS A MANUTENÇÃO DA ESTRUTURA DE ARMAZENAMENTO



-- SALVAR ESTE ARQUIVO COMO: SCRIPT_DDL_COMANDOS_ADICIONAIS.SQL



-- O FOCO É TRABALHAR O COMANDO ALTER TABLE



-- CRIAREMOS UMA ESTRUTURA EXEMPLO, PARA APLICARMOS OS COMANDOS DDL (ALTER TABLE)
CREATE TABLE T_TESTE_DDL
(
CD_TESTE NUMBER(3) NOT NULL ,
NM_TESTE VARCHAR2(30) NOT NULL ,
DS_TESTE VARCHAR2(60) NULL ,
DT_TESTE DATE NULL
);
-- CHAVE PRIMARIA
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT PK_TESTE_DDL PRIMARY KEY (CD_TESTE);
-- CONSTRAINT UNIQUE
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT UN_TESTE_DDL_NOME UNIQUE (NM_TESTE);
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT UN_TESTE_DDL_DESC UNIQUE (DS_TESTE);

-----------------------------------------------------------------------------
-- COMO ADICIONAR UMA COLUNA(CAMPO) EM UMA TABELA JÁ EXISTENTE?
-- UTILIZAMOS A OPÇÃO: ADD

ALTER TABLE T_TESTE_DDL
        ADD DS_EMAIL VARCHAR2(80);
        
ALTER TABLE T_TESTE_DDL
        ADD (DS_OBS1 VARCHAR2(50)NOT NULL , DS_OBS2 VARCHAR2(50))
        

-- COMO MODIFICAR UMA COLUNA DE UMA TABELA JÁ EXISTENTE?
-- UTILIZAMOS A OPÇÃO: MODIFY
-- COMO AUMENTAR O TAMANHO DE UMA COLUNA?
-- AUMENTAR O CAMPO OBSERVAÇÃO 1 PARA 80 CARACTERES
ALTER TABLE T_TESTE_DDL
    MODIFY DS_OBS1 VARCHAR2(80);
    

-- COMO MODIFICAR O TIPO DE DADO DE UMA COLUNA?
-- ALTERAR O TIPO DE DADO DA COLUNA NM_TESTE PARA CHAR(30) - MANTER O MESMO TAMANHO
ALTER TABLE T_TESTE_DDL
    MODIFY NM_TESTE CHAR(30);


-- COMO ALTERAR UMA COLUNA NULL (OPCIONAL) PARA NOT NULL (OBRIGATORIA) ?
-- FAZER A ALTERAÇÃO PARA A COLUNA DS_TESTE
ALTER TABLE T_TESTE_DDL
    MODIFY DS_TESTE NOT NULL;
    

-- COMO ALTERAR UM VALOR DEFAULT (INSERIR UM VALOR DEFAULT)
-- VALOR DEFAULT SYSDATE PARA A COLUNA/CAMPO DT_TESTE (SYSDATE - FUNÇÃO DO ORACLE QUE RETORNA DATA/HORA DO SERVIDOR)
ALTER TABLE T_TESTE_DDL
    MODIFY DT_TESTE DEFAULT SYSDATE; 
    
    
-- COMO ALTERAR UMA COLUNA NOT NULL (OBRIGATORIA) PARA NULL (OPCIONAL)
-- PARA O CAMPO/COLUNA DS_OBS1
ALTER TABLE T_TESTE_DDL
    MODIFY DS_OBS1 NULL;
    
    
-- COMO MODIFICAR TIPO DE DADO, TAMANHO E OBRIGATORIEDADE DE UMA COLUNA ?
-- ALTERAR A COLUNA NM_TESTE -> VARCHAR2 COM TAMANHO 40 OPCIONAL (NULL)
ALTER TABLE T_TESTE_DDL
    MODIFY NM_TESTE VARCHAR2(40) NULL;
    
    
-- COMO APAGAR UMA COLUNA DA TABELA?
-- ELIMINAR A COLUNA DS_OBS2
ALTER TABLE T_TESTE_DDL
DROP COLUMN DS_OBS2;


-- COMO APAGAR VÁRIAS COLUNAS DA TABELA
-- ELIMINAR A COLUNA DS_TESTE e DS_OBS1
ALTER TABLE T_TESTE_DDL
DROP (DS_TESTE, DS_OBS1)


-- COMO APAGAR UMA CONSTRAINT CHAVE PRIMARIA
-- UTILIZAMOS A OPÇÃO: DROP CONSTRAINT
-- PONTO DE ATENÇÃO: PARA OS RELACIONAMENTOS, ONDE UMA CHAVE ESTRANGEIRA APONTA PARA UMA CHAVE PRIMARIA, PRECISAMOS
-- NO MOMENTO QUE APAGAR A CONSTRAINT, ELIMINAR O RELACIONAMENTO
-- PARA ELIMINAR O VINCULO DO RELACIONAMENTO, PRECISAMOS INCLUIR A OPÇÃO CASCADE (ELIMINAR O RELACIONAMENTO)
    ALTER TABLE T_TESTE_DDL
DROP CONSTRAINT PK_TESTE_DDL;


-- SE A TABELA POSSUIR RELACIONAMENTOS, INCLUIR A OPCAO CASCADE.
    ALTER TABLE T_TESTE_DDL
DROP CONSTRAINT PK_TESTE_DDL CASCADE;


-- AS DEMAIS CONSTRAINTS SÃO ELIMINADAS, E NÃO HÁ A OPÇÃO CASCADE
-- EXEMPLO DE ELIMINAÇÃO DE OUTRAS CONSTRAINTS
    ALTER TABLE T_TESTE_DDL
DROP CONSTRAINT UN_TESTE_DDL_NOME;
-- PARA OUTRAS CONSTRAINTS (CHECK E FK)
-- ALTER TABLE T_TESTE_DDL DROP CONSTRAINT CK_<NOME DA CONSTRAINT>;
-- ALTER TABLE T_TESTE_DDL DROP CONSTRAINT FK_<NOME DA CONSTRAINT>;

-- COMO ELIMINAR UMA CONSTRAINT DEFAULT
ALTER TABLE T_TESTE_DDL
    MODIFY DT_TESTE DEFAULT NULL;  


-- COMO RENOMEAR UMA TABELA
-- UTILIZAMOS A OPÇÃO: RENAME TO
ALTER TABLE T_TESTE_DDL RENAME TO T_TESTE_DDL_NOVO;


-- COMO RENOMEAR UMA COLUNA (CAMPO)
-- UTILIZAMOS A OPÇÃO: RENAME COLUMN
    ALTER TABLE T_TESTE_DDL_NOVO
RENAME COLUMN DS_EMAIL TO DS_EMAIL_NOVO;


-- CRIAR A CONSTRAINT NOVAMENTE PARA PODER RENOMEAR
    ALTER TABLE T_TESTE_DDL_NOVO 
ADD CONSTRAINT UN_TESTE_DDL_NOME UNIQUE (NM_TESTE);


-- COMO RENOMEAR UMA CONSTRAINT (QUALQUER CONSTRAINT: PK, FK, CHECK, UNIQUE)
-- UTILIZAMOS A OPÇÃO: RENAME CONSTRAINT
    ALTER TABLE T_TESTE_DDL_NOVO 
    RENAME CONSTRAINT UN_TESTE_DDL_NOME TO UN_TESTE_DDL_NOME_NOVO;


-- PARA HABILITAR E DESABILITAR CONSTRAINTS
-- QUANDO CRIAMOS UMA CONSTRAINT, ELA "NASCE" HABILITADA, OU SEJA, PRONTA PARA SER UTILIZADA DURANTE O CRUD
-- PODEMOS "DESLIGAR" UMA CONSTRAINT, E UMA VEZ DESLIGADA, ELA NÃO E CONSIDERADA DURANTE UM CRUD
-- COMO DESABILITAR UMA CONSTRAINT
-- UTILIZAMOS A OPÇÃO: DISABLE
    ALTER TABLE T_TESTE_DDL_NOVO 
DISABLE CONSTRAINT UN_TESTE_DDL_NOME_NOVO;

-- COMO HABILITAR UMA CONSTRAINT
-- UTILIZAMOS A OPÇÃO: ENABLE
    ALTER TABLE T_TESTE_DDL_NOVO 
ENABLE CONSTRAINT UN_TESTE_DDL_NOME_NOVO;


-- COMENTARIO SOBRE A TABELA 
COMMENT ON TABLE T_TESTE_DDL_NOVO IS 'TABELA UTILIZADA PARA EXEMPLIFICAR COMANDOS DDL';


-- COMENTARIO SOBRE A COLUNA 
COMMENT ON COLUMN T_TESTE_DDL_NOVO.NM_TESTE IS 'COLUNA CONTENDO O NOME DO TESTE';


-- VISUALIZAR A DESCRICAO DE UMA TABELA
DESCRIBE T_TESTE_DDL_NOVO;

-- VISUALIZAR A DESCRICAO DE UMA TABELA
DESC T_TESTE_DDL;


-- CONSULTANDO COMENTARIOS DA TABELA E COLUNA
-- SINTAXE BASICA 
-- SELECT <NOME DA COLUNA(S)> - CONSULTA E DIZ QUAIS COLUNAS 
-- FROM <NOME_TABELA(S)> - QUAL TABELA(S) DESEJA CONSULTAR
-- WHERE <CONDICAO> - PARA FILTRAR O RESULTADO CONSULTADO
SELECT COMMENTS 
    FROM ALL_TAB_COMMENTS -- TABELA DO ORACLE QUE ARMAZENA OS COMENTARIOS
    WHERE TABLE_NAME = 'T_TESTE_DDL_NOVO' 


--CONSULTA COMENTARIO DA CULUNA 
SELECT COMMENTS 
    FROM ALL_COL_COMMENTS -- TABELA DO ORACLE QUE ARMAZENA OS COMENTARIOS
    WHERE TABLE_NAME = 'T_TESTE_DDL_NOVO' AND 
    COLUMN_NAME = 'NM_TESTE';
    

-- ASSOCIAR A CONSULTA COM A TABELA TESTE QUE CRIAMOS
SELECT CD_TESTE, NM_TESTE
    FROM T_TESTE_DDL_NOVO


    
-- PARA EXECUTAR 
-- F5, RESULTADO APARECE NA SAIDA DO SCRIPT
-- <CTRL>+<ENTER> , O RESULTADO APARECE NO RESULTADO DA CONSULTA (FORMA TABULAR MAIS AMIGAVEL)


