-- 2
CREATE SEQUENCE SQ_SLV_AUTOR
      START WITH 1
    INCREMENT BY 1 
        MAXVALUE 999
         NOCACHE
         NOCYCLE;
         
CREATE SEQUENCE SQ_SLV_CATEGORIA
      START WITH 1
    INCREMENT BY 1 
        MAXVALUE 999
         NOCACHE
         NOCYCLE;
         

-- 3
INSERT INTO T_SLV_AUTOR VALUES (SQ_SLV_AUTOR.NEXTVAL, 'AUTOR', 'SOBRENOME AUTOR', 'AUTOR@AUTOR.COM', 'PAIS');

SELECT * FROM T_SLV_AUTOR;

-- 4
INSERT INTO T_SLV_CATEGORIA VALUES (SQ_SLV_CATEGORIA.NEXTVAL, 'SC', 'CATEGORIA C');         

-- 5 
SELECT SQ_SLV_CATEGORIA.NEXTVAL FROM DUAL;

-- 6 
INSERT INTO T_SLV_CATEGORIA VALUES (SQ_SLV_CATEGORIA.NEXTVAL, 'SD', 'CATEGORIA D');         

-- 7
SELECT * FROM T_SLV_CATEGORIA;
-- HOUVE GAP DEVIDO AO COMANDO SELECT USADO ANTERIORMENTE COM NEXTVAL

-- 8
SELECT SQ_SLV_CATEGORIA.CURRVAL FROM DUAL;

SELECT SQ_SLV_AUTOR.CURRVAL FROM DUAL;

COMMIT;




