--------------------------------------------------------
--  SCRIPT DRS - EXEMPLOS DE FUNÇÕES SQL / ORACLE
--------------------------------------------------------
-- 01 --

-- FUNÇÕES DE CONVERSÃO DE ESCRITA
SELECT F.NM_FUNCIONARIO           "COMO ESTÁ GRAVADO"  ,
       LOWER(F.NM_FUNCIONARIO)    "MINUSCULAS (LOWER)" ,
       UPPER(F.NM_FUNCIONARIO)    "MAIUSCULAS (UPPER)" ,
       INITCAP(F.NM_FUNCIONARIO)  "MAIUSCULA/MINUSCULA (INITCAP)" 
  FROM T_SIP_FUNCIONARIO F;

-- FUNÇÕES ASCII(X) E CHAR(X)
SELECT ASCII('R'), CHR(82) FROM DUAL;

-- FUNÇÃO CONCAT(X,Y)
SELECT CONCAT(CONCAT(F.NR_MATRICULA,'-'),F.NM_FUNCIONARIO)           
  FROM T_SIP_FUNCIONARIO F;

-- FUNÇÃO INSTR(X,STRING, INICIO, OCORRENCIA)  
SELECT F.NM_FUNCIONARIO                ,
       INSTR(F.NM_FUNCIONARIO,'A')     ,
       INSTR(F.NM_FUNCIONARIO,'JOS')     ,
       INSTR(F.NM_FUNCIONARIO,'A',3)   ,
       INSTR(F.NM_FUNCIONARIO,'A',3,2)
  FROM T_SIP_FUNCIONARIO F;
  
-- FUNÇÃO LENGTH(X)  
SELECT F.NM_FUNCIONARIO , 
       LENGTH(F.NM_FUNCIONARIO)   "TAMANHO EM NUMERO DE CARACTERES" 
  FROM T_SIP_FUNCIONARIO F;

-- FUNÇÃO TRIM, RTRIM, LTRIM
SELECT F.NM_FUNCIONARIO                ,   
       LTRIM(F.NM_FUNCIONARIO)         ,
       LTRIM(F.NM_FUNCIONARIO, 'A')    , 
       RTRIM(F.NM_FUNCIONARIO)         ,  
       RTRIM(F.NM_FUNCIONARIO, 'O')    ,     
       TRIM(F.NM_FUNCIONARIO) ,
       TRIM('A' FROM F.NM_FUNCIONARIO)     
  FROM T_SIP_FUNCIONARIO F;

SELECT D.NM_DEPTO        ,
       LTRIM(D.NM_DEPTO) ,
       TRIM(D.NM_DEPTO)
  FROM T_SIP_DEPTO D;      

-- 02 --

-- FUNÇÃO LPAD(X, LARGURA, STRING PREENCHIMENTO)  E  RPAD(X, LARGURA, STRING PREENCHIMENTO)
SELECT F.NM_FUNCIONARIO                ,
       F.VL_SALARIO_MENSAL             ,
       RPAD(F.NM_FUNCIONARIO,60)       ,
       RPAD(F.NM_FUNCIONARIO,60,'.')   ,
       LPAD(VL_SALARIO_MENSAL,10,'*')   
  FROM T_SIP_FUNCIONARIO F;

-- FUNÇÃO NVL(X, VALOR) E NVL2(X, VALOR1, VALOR2)
SELECT F.DT_TERMINO ,
       NVL(F.DT_TERMINO,'01/01/1900'),
       NVL2(F.DT_TERMINO,SYSDATE,'01/01/1900')       
  FROM T_SIP_PROJETO F;  



-- FUNÇÃO REPLACE (X, STRING_BUSCA, STRING_SUBSITUICAO)
SELECT F.NM_FUNCIONARIO                ,
       REPLACE(F.NM_FUNCIONARIO,'A','*')
  FROM T_SIP_FUNCIONARIO F;
  
-- FUNÇÃO SUBSTR(X, INICIO, COMPRIMENTO)
SELECT F.NM_FUNCIONARIO                ,
       SUBSTR(F.NM_FUNCIONARIO,3)      ,
       SUBSTR(F.NM_FUNCIONARIO,3, 5)      
  FROM T_SIP_FUNCIONARIO F;
  
-- ROUND(X,Y) , MOD(X,Y), TRUNC(X,Y), SQRT(X), ABS(X)
SELECT F.VL_SALARIO_MENSAL           ,
       ROUND(F.VL_SALARIO_MENSAL)    ,
       ROUND(F.VL_SALARIO_MENSAL,1)  ,
       TRUNC(F.VL_SALARIO_MENSAL)    ,
       TRUNC(F.VL_SALARIO_MENSAL,1)  ,
       MOD(F.VL_SALARIO_MENSAL,3)    ,
       ABS(F.VL_SALARIO_MENSAL)      ,
       SQRT(F.VL_SALARIO_MENSAL)
  FROM T_SIP_FUNCIONARIO F;


-- 03-- 

-- FUNÇÃO TO_CHAR()
SELECT F.VL_SALARIO_MENSAL ,
       TO_CHAR(F.VL_SALARIO_MENSAL, 'L9999999.99') "SIMBOLO MOEDA LOCAL" ,
       TO_CHAR(F.VL_SALARIO_MENSAL, 'C99,999.99') "SIMBOLO MOEDA ISO" ,
       TO_CHAR(F.VL_SALARIO_MENSAL, '99,999.99')  ,
       F.NR_MATRICULA ,
       TO_CHAR(F.NR_MATRICULA, '0099999')       
  FROM T_SIP_FUNCIONARIO F;

SELECT TO_CHAR(12345678, '0099999999') ,
       TO_CHAR(1234.56,'C99,999.99')  "SIMBOLO MOEDA ISO" ,
       TO_CHAR(-120.30,'99,999.99')
  FROM DUAL;
  
-- FUNÇÃO TO_NUMBER()  
SELECT TO_NUMBER('103')      ,
       TO_NUMBER('103') + 30 ,
       TO_NUMBER('-$12,345.99','$99,999.99')
  FROM DUAL;

-- ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY HH:MI:SS';
-- ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY';

-- FUNÇÃO TO DATE()
SELECT F.DT_ADMISSAO ,
       TO_DATE(F.DT_ADMISSAO,'DD/MM/YYYY')  
  FROM T_SIP_FUNCIONARIO F;

-- FUNÇÃO CAST()
-- CONVERTER VALORES LITERAIS EM TIPOS ESPECIFICOS
SELECT 
        CAST(12345.67 AS VARCHAR2(10) ) ,        
        CAST('29/09/2021' AS DATE ) ,
        CAST(12345.678 AS NUMBER(10,2) ) 
  FROM DUAL;


-- CONVERTER VALORES DE COLUNA DE UM TIPO PARA OUTRO
SELECT 
       CAST (F.VL_SALARIO_MENSAL AS VARCHAR2(10) ) ,
       CAST (F.VL_SALARIO_MENSAL + 1000 AS NUMBER (8,2))
  FROM T_SIP_FUNCIONARIO F;


-- ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY HH:MI:SS';

-- 04 --

-- EXEMPLO SYSDATE
SELECT SYSDATE FROM DUAL;

-- SOMANDO OU SUBTRAINDO MESES DE UMA DATA
SELECT SYSDATE                 "DATA ATUAL",
       ADD_MONTHS(SYSDATE, 1)  "PRÓXIMO MÊS",
       ADD_MONTHS(SYSDATE, -1) "MÊS ANTERIOR"
  FROM DUAL;

SELECT DT_ADMISSAO ,
       ADD_MONTHS(DT_ADMISSAO,1) 
  FROM T_SIP_FUNCIONARIO;
  
-- RETORNANDO O ÚLTIMO DIA DO MÊS DE UMA DATA
SELECT SYSDATE "DATA ATUAL" ,
       LAST_DAY(SYSDATE) "DATA COM ÚLTIMO DIA DO MÊS"
  FROM DUAL;
  
SELECT DT_ADMISSAO ,
       LAST_DAY(DT_ADMISSAO) 
  FROM T_SIP_FUNCIONARIO;

-- ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY';

-- QUANTIDADE DE MESES ENTRE DUAS DATAS
SELECT DT_ADMISSAO ,
       SYSDATE , 
       MONTHS_BETWEEN(SYSDATE, DT_ADMISSAO) ,
       TRUNC(MONTHS_BETWEEN(SYSDATE, DT_ADMISSAO)) || ' MESES'
  FROM T_SIP_FUNCIONARIO;
  
-- RECUPERA O PRÓXIMO DIA DE UMA DATA INFORMADA
SELECT SYSDATE ,
       NEXT_DAY(SYSDATE, 1) "PRÓXIMO DOMINGO" ,
       NEXT_DAY(SYSDATE, 2) "PRÓXIMA SEGUNDA" ,
       NEXT_DAY(SYSDATE, 3) "PRÓXIMA TERÇA" ,
       NEXT_DAY(SYSDATE, 4) "PRÓXIMA QUARTA" ,
       NEXT_DAY(SYSDATE, 5) "PRÓXIMA QUINTA" ,
       NEXT_DAY(SYSDATE, 6) "PRÓXIMA SEXTA" ,
       NEXT_DAY(SYSDATE, 7) "PRÓXIMO SÁBADO" 
  FROM DUAL;

-- 05 --

-- RETORNAR O ANO DE CONTRATAÇÃO DE UM FUNCIONÁRIO
SELECT DT_ADMISSAO ,
       TO_CHAR(DT_ADMISSAO, 'YYYY') "ANO CONTRATACAO" ,
       TO_CHAR(DT_ADMISSAO, 'MM/YYYY') "MÊS E ANO CONTRATACAO" ,
       TO_CHAR(DT_ADMISSAO, 'DD/MM') "DIA E MÊS DA CONTRATACAO" ,
       TO_CHAR(DT_ADMISSAO, 'DD " de " fmMONTH " de " YYYY', 'NLS_DATE_LANGUAGE=PORTUGUESE') "DATA POR EXTENSO"
  FROM T_SIP_FUNCIONARIO;

-- MAIS FUNÇÕES COM DATA
-- ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY';

SELECT DT_ADMISSAO ,
       TO_DATE(DT_ADMISSAO , 'DD/MM/YYYY') - 5,
       TO_DATE(SYSDATE, 'DD/MM/YYYY') - TO_DATE(DT_ADMISSAO, 'DD/MM/YYYY')
  FROM T_SIP_FUNCIONARIO;
  


-- ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY HH:MI:SS';  

SELECT DT_ADMISSAO ,
       TO_DATE(DT_ADMISSAO,'DD/MM/YYYY HH:MI:SS') + 6/24
  FROM T_SIP_FUNCIONARIO;
  