-- SCRIPT DML -> LINGUAGEM DE MANUTENÇÃO DE DADOS 
-- TEMOS OS COMANDOS:
-- INSERT ->PARA INSERIR LINHAS/REGISTROS NAS ESTRUTURA (NO BD)
-- UPDATE -> PARA ALTERAR UMA OU MAIS COLUNAS/CAMPO, AFETANDO UMA OU MAIS LINHAS/REGISTROS NA ESTRUTURA
-- DELETE -> PARA ELIMINAR UMA OU MAIS LINHAS/REGISTROS NA ESTRUTURA
-- COMANDOS QUE REPRESENTAM O CRUD NA PROGRAMAÇÃO
-- C = CREATE, R = READ, U = UPDATE, D = DELETE // TEMOS OS COMANDOS DE PERSISTÊNCIA 

-- INSERINDO LINHAS/REGSITROS NA TABELA
INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
    VALUES (1, 'FINANCEIRO', 'FIN');


-- INSERINDO LINHAS/REGISTROS NA TABELA, INFORMANDO APENAS O CONTEUDO
-- O CONTEUDO INFORMADO NO VALUES, PRECISA ESTAR NA ORDEM DA CRIAÇÃO DA TABELA
INSERT INTO T_SIP_DEPTO VALUES (2, 'MARKETING', 'MKT');


-- SELECT (CONSULTAR)
-- FROM (INFORMA QUAIS TABELAS DEVEM SER CONSULTADAS)
SELECT * FROM T_SIP_DEPTO;-- RECUPERAR/CONSULTAR TODAS AS COLUNAS E LINHAS DA TABELA DEPTO


-- INSERÇÃO CONTENDO DATA/HORA
INSERT INTO T_SIP_PROJETO VALUES (1, 'PROJETO ABC',
                                  TO_DATE('01/02/2018', 'DD/MM/YYYY'),
                                  TO_DATE('15/10/2020', 'DD/MM/YYYY')
                                  );
-- FUNÇÃO TO_DATE (<TEXTO NO FORMATO DATA/HORA>,<FORMATAÇÃO>)
-- CONVERTE UM TEXTO PARA A DATA NO FORMATO ESPECIFICADO 

SELECT * FROM T_SIP_PROJETO;             
                                  
-- PONTO DE ATENÇÃO
-- DATA ENVIADA                                  FORMATO DE DATA ESPERADO (SERVIDOR ORACLE)
-- TO DATE('01/02/2018', 'DD/MM/YYYY')           MM/DD/YYYY
-- DD=01, MM=02, YYYY=2018                       02/01/2018
-- '28/05/2019'                                  MM=28, DD=05, YYYY=2019 XXX ERRO 

-- INSERÇÃO CONTENDO NUMEROS DECIMAIS
-- INSERÇÃO NA TABELA FUNCIONÁRIO - TEMOS O SALÁRIO 
INSERT INTO T_SIP_FUNCIONARIO VALUES(12345, 1, -- 1 É O DEPTO QUE ESTÁ CADASTRADO (FK)
                               'JOAO DA SILVA XAVIER',
                               TO_DATE('18/03/1985', 'DD/MM/YYYY'),
                               TO_DATE('25/08/2011', 'DD/MM/YYYY'),
                               'AV.SAO LOURENÇO, 1171',
                               3843.85);

-- SO PODEMOS INFORMAR UM VALOR PARA CHAVE ESTRANGEIRA, QUE ESXISTA CADASTRADO NA TABELA DEPTO 
-- DEVIDO A INTREGRIDADE REFERENCIAL DO RELACIONAMENTO

-- PARA VALORES DECIMAIS UTILIZAMOS O PONTO DECIMAL, CASO SEJA UTILIZADO A VIRGULA, DARA ERRO, POIS SERA
-- ENTENDIDO COMO SEPARAÇÃO DOS VALORES PARA INSERÇÃO
SELECT * FROM T_SIP_FUNCIONARIO;             


-- INSERINDO VALORES NULOS PARA CAMPOS OPCIONAIS
-- MÉTODO IMPLÍCITO - OMITA A COLUNA DA LISTA DE COLUNAS 
-- INSERÇÃO NA TABELA PROJETO, QUE POSSUI A DATA TERMINO COMO CAMPO OPCIONAL
INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO) -- DECLARAMOS AS COLUNAS A SEREM INSERIDAS, OMITINDO A OPCIONAL
    VALUES (2, 'PROJETO DEF', TO_DATE('14/03/2019', 'DD/MM/YYYY'));

SELECT * FROM T_SIP_PROJETO; 
-- APÓS A EXECUÇÃO, OBSERVAMOS QUE O CAMPO DATA_TERMINO É PREENCHIDO COM NULO, POIS É OPCIONAL

-- MÉTODO EXPLÍCITO - ESPECIFIQUE A PALAVRA-CHAVE NULL, NA CLAUSULA VALUES
INSERT INTO T_SIP_PROJETO VALUES (3, 'PROJETO GHI', TO_DATE('30/08/2020', 'DD/MM/YYYY'), NULL);

SELECT * FROM T_SIP_PROJETO; 


-- REALIZANDO COPIA DE DADOS DE UMA TABELA PARA OUTRA
-- CRIAR UMA TABELA PARA REALIZAR A CÓPIA
CREATE TABLE T_SIP_COPY_PROJETO_FIN
(
CD_PROJETO NUMBER(5) NOT NULL ,
NM_PROJETO VARCHAR2(40) NOT NULL ,
DT_INICIO DATE NOT NULL ,
DT_TERMINO DATE NOT NULL
);



-- CHAVE PRIMARIA DA TABELA COPIA PROJETOS FINALIZADOS
ALTER TABLE T_SIP_COPY_PROJETO_FIN
ADD CONSTRAINT PK_SIP_COPY_PROJETO_FIN
PRIMARY KEY (CD_PROJETO);


-- REALIZANDO A COPIA DOS DADOS DE UMA TABELA PARA OUTRA
-- UTILIZANDO O COMANDO INSERT E O COMANDO SELECT (SUBCONSULTA OU SUBQUERY)
INSERT INTO T_SIP_COPY_PROJETO_FIN (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
    (SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO
        FROM T_SIP_PROJETO
     WHERE DT_TERMINO IS NOT NULL);


-- DESTA FORMA NÃO FUNCIONA, PORQUE NULO NAO TEM VALOR
-- DT_TERMINO = NULL
-- DT_TERMINO <> NULL-- FUNCIONA APENAS DESTA FORMA
-- DT_TERMINO IS NULL -> DT_TERMINO E IGUAL A NULO
-- DT_TERMINO IS NOT NULL -> DT_TERMINO E DIFERENTE DE NULO

SELECT * FROM T_SIP_COPY_PROJETO_FIN;

-- OU
-- QUANDO AS TABELAS POSSUEM A MESMA ESTRUTURA E MESMO NOME DAS COLUNAS, NA MESMA ORDEM, PODEMOS FAZER DESTA FORMA
INSERT INTO T_SIP_COPY_PROJETO_FIN (SELECT* FROM T_SIP_PROJETO WHERE DT_TERMINO IS NOT NULL);



-- EXEMPLOS DE COMANDO UPDATE
-- ALTERAR O NOME E A DATA DE NACIMENTO DE UM FUNIONARIO ESPECIFICO 

UPDATE T_SIP_FUNCIONARIO
    SET NM_FUNCIONARIO = 'JOAO DA SILVA XAVIER DE CAMARGO',
        DT_NASCIMENTO = TO_DATE('18/05/85', 'DD/MM/YY')
    WHERE NR_MATRICULA = 12345;

-- ATUALIZAR O SALARIO DOS FUNCIONARIOS
-- TODOS OS FUNCIONARIOS IRÃO RECEBER UM AUMENTO DE 5%

UPDATE T_SIP_FUNCIONARIO
    SET VL_SALARIO_MENSAL = VL_SALARIO_MENSAL * 1.05;
-- NAO TEMOS A CLAUSULA WHERE, POIS O AUMENTO É PARA TODOS OS FUNCIONARIOS 

UPDATE T_SIP_PROJETO
    SET DT_TERMINO = 
        (SELECT DT_TERMINO
            FROM T_SIP_COPY_PROJETO_FIN
         WHERE CD_PROJETO = 1);

SELECT * FROM T_SIP_PROJETO;


-- EXEMPLOS DE COMANDO DELETE
-- ELIMINAR OS FUNCIONARIOS DO DEPTO FINANCEIRO (COD=1) E QUE
-- FORAM ADMITIDOS A PARTIR DE 2011

DELETE FROM T_SIP_FUNCIONARIO 
    WHERE CD_DEPTO = 5 AND DT_ADMISSAO >= TO_DATE('01/01/17', 'DD/MM/YY');


-- DELEÇÃO COM SUBCONSULTA
-- ELIMINAR O PROJETO NA TABELA PROJETO, CORRESPONDENTE AO PROJETO QUE FOI
-- COPIADO PARA A TABELA COPY_PROJETO_FIN

DELETE FROM T_SIP_PROJETO
    WHERE CD_PROJETO = 
        (SELECT CD_PROJETO 
            FROM T_SIP_COPY_PROJETO_FIN
         WHERE NM_PROJETO = 'PROJETO ABC');

-- EXEMPLO COM ROLLBACK
-- DESFAZ A TRANSACAO, CASO NÃO TENHA SIDO APLICADO AINDA O COMANDO COMMIT
ROLLBACK;






-- PARA ALTERAR O FORMATO DA DATA/HORA NA SESSÃO ABERTA NO SQLDEVELOPER
ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';

ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi';

ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy';


-- COMMIT -> PARA EFETIVAR AS TRANSAÇÕES EM DISCO
-- PODE SER UM COMMIT PARA VÁRIAS INSTRUÇÕES INSERT/UPDATE/DELETE
COMMIT;



-- ERROS COMUNS

-- ERROS POSSIVEIS
-- ERRO DE VIOLAÇÃO DE CHAVE PRIMARIA
-- INFORMAR UMA CHAVE PRIMARIA JÁ EXISTENTE
INSERT INTO T_SIP_DEPTO VALUES(1, 'TESTE', 'TST');
/*    
Erro a partir da linha : 132 no comando -
INSERT INTO T_SIP_DEPTO VALUES(1, 'TESTE', 'TST')
Relatório de erros -
ORA-00001: restrição exclusiva (RM88670.PK_SIP_DEPTO) violada
*/  

-- ERRO DE VIOLAÇÃO DE UNIQUE CONSTRAINT
-- INFORMAR UM NOME DE DEPTO QUE JÁ EXISTE
INSERT INTO T_SIP_DEPTO VALUES (3, 'MARKETING', 'MKT');
/*
Erro a partir da linha : 142 no comando -
INSERT INTO T_SIP_DEPTO VALUES (3, 'MARKETING', 'MKT')
Relatório de erros -
ORA-00001: restrição exclusiva (RM88670.UN_SIP_DEPTO_NOME) violada
*/

-- ERRO DE VIOLAÇÃO DE CHAVE ESTRANGEIRA
-- INFORMAR UM CODIGO DE DEPTO QUE NÃO ESTA CADASTRADO NA TAB. DEPTO
INSERT INTO T_SIP_FUNCIONARIO VALUES (12349, 99, -- PROVOCAR ERRO DE FK, CODIGO NAO EXISTE)
                                      'TESTE', TO_DATE('01/01/1980', 'DD/MM/YYYY'),
                                      TO_DATE('10/10/2011', 'DD/MM/YYYY'),
                                      'RUAX, 25', 2800.60);
/*
Erro a partir da linha : 152 no comando -
INSERT INTO T_SIP_FUNCIONARIO VALUES (12349, 99, -- PROVOCAR ERRO DE FK, CODIGO NAO EXISTE)
                                      'TESTE', TO_DATE('01/01/1980', 'DD/MM/YYYY'),
                                      TO_DATE('10/10/2011', 'DD/MM/YYYY'),
                                      'RUAX, 25', 2800.60)
Relatório de erros -
ORA-02291: restrição de integridade (RM88670.FK_SIP_FUNC_DEPTO) violada - chave mãe não localizada
*/

-- ERRO DE VIOLAÇÃO DE CHECK CONSTRAINT
-- INFORMAR UM SALARIO MENOR QUE O VALOR QUE TEMOS NA CHECK
-- CHECK -> VL_SALARIO >= 1045
INSERT INTO T_SIP_FUNCIONARIO VALUES(12349, 1, -- PROVOCAR ERRO DE FK, CODIGO NAO EXISTE)
                                      'TESTE', TO_DATE('01/01/1980', 'DD/MM/YYYY'),
                                      TO_DATE('10/10/2011', 'DD/MM/YYYY'),
                                      'RUAX, 25', 600.60);
/*
Erro a partir da linha : 169 no comando -
INSERT INTO T_SIP_FUNCIONARIO VALUES(12349, 1, -- PROVOCAR ERRO DE FK, CODIGO NAO EXISTE)
                                      'TESTE', TO_DATE('01/01/1980', 'DD/MM/YYYY'),
                                      TO_DATE('10/10/2011', 'DD/MM/YYYY'),
                                      'RUAX, 25', 600.60)
Relatório de erros -
ORA-02290: restrição de verificação (RM88670.CK_SIP_FUNC_SALARIO) violada
*/

-- ERRO REFERENTE AO TAMANHO DE DADOS
-- INFORMAR 5 DIGITOS PARA O CODIGO DO DEPTO, ONDE SÃO ESPERADOS APENAS 3
INSERT INTO T_SIP_DEPTO VALUES (11111, 'TESTE DEPTO', 'TST');
/*
Erro a partir da linha : 185 no comando -
INSERT INTO T_SIP_DEPTO VALUES (11111, 'TESTE DEPTO', 'TST')
Relatório de erros -
ORA-01438: valor maior que a precisão especificada usado para esta coluna
*/

INSERT INTO T_SIP_DEPTO VALUES (99, 'TESTE DEPTO', 'TST123');
/*
Erro a partir da linha : 193 no comando -
INSERT INTO T_SIP_DEPTO VALUES (99, 'TESTE DEPTO', 'TST123')
Relatório de erros -
ORA-12899: valor muito grande para a coluna "RM88670"."T_SIP_DEPTO"."SG_DEPTO" (real: 6, máximo: 3)
*/

-- ERRO DE TIPO DE DADOS
-- INFORMAR UM CONTEÚDO CARACTERE, ONDE E ESPERADO NUMERO
INSERT INTO T_SIP_DEPTO VALUES ('XXX', 'TESTE', 'TST');
/*
Erro a partir da linha : 203 no comando -
INSERT INTO T_SIP_DEPTO VALUES ('XXX', 'TESTE', 'TST')
Relatório de erros -
ORA-01722: número inválido
*/

-- ERRO DE VALORES INSUFICIENTES PARA A INSERÇÃO
INSERT INTO T_SIP_DEPTO VALUES (99, 'APENAS NOME-TESTE'); -- ENVIADO APENAS CODIGO E NOME, FALTA A SIGLA 
/*
rro a partir da linha : 212 no comando -
INSERT INTO T_SIP_DEPTO VALUES (99, 'APENAS NOME-TESTE')
Erro na Linha de Comandos : 212 Coluna : 13
Relatório de erros -
Erro de SQL: ORA-00947: não há valores suficientes
00947. 00000 -  "not enough values"
*Cause:    
*Action:
*/

-- ERRO DE VALORES A MAIS DO QUE O ESPERADO
INSERT INTO T_SIP_DEPTO VALUES (99, 'TESTE', 'TST', 'CAMPO A MAIS'); -- ENVIANDO UM VALOR A MAIS
/*
Erro a partir da linha : 225 no comando -
INSERT INTO T_SIP_DEPTO VALUES (99, 'TESTE', 'TST', 'CAMPO A MAIS')
Erro na Linha de Comandos : 225 Coluna : 13
Relatório de erros -
Erro de SQL: ORA-00913: valores demais
00913. 00000 -  "too many values"
*Cause:    
*Action:
*/

-- SUGESTÃO -- ERROS DE SINTAXE
-- FALTOU A PALAVRA VALUES
INSERT INTO T_SIP_DEPTO (99, 'TESTE', 'TST');
/*
Erro a partir da linha : 239 no comando -
INSERT INTO T_SIP_DEPTO (99, 'TESTE', 'TST')
Erro na Linha de Comandos : 239 Coluna : 26
Relatório de erros -
Erro de SQL: ORA-00928: palavra-chave SELECT não encontrada
00928. 00000 -  "missing SELECT keyword"
*Cause:    
*Action:
*/





