/*
Bruno Biancchi – RM 84351
Luis Henrique Caldas Altero – RM 88670
Pedro Guilherme Polloni Barreto - RM 88964
Victor Lamprecht Di Roberto – RM 86691
*/

/*
SELECT * FROM t_src_instituicao_caridade;
SELECT * FROM t_src_localizacao;
SELECT * FROM t_src_posto_coleta;
SELECT * FROM t_src_reciclavel;
SELECT * FROM t_src_doador;
SELECT * FROM t_src_doacao;
*/


-- RECUPERANDO AS INSTITUIÇÕES QUE RECEBERAM MAIS DOAÇÃO 
    SELECT 
      IC.NM_INSTITUICAO "INSTITUIÇÕES", 
      COUNT(DOA.CD_DOACAO)  "QUANTIDADE DE DOAÇÕES"
        FROM T_SRC_INSTITUICAO_CARIDADE IC
    LEFT JOIN T_SRC_DOADOR D 
        ON IC.CD_INSTITUICAO = D.CD_INSTITUICAO
    LEFT JOIN T_SRC_DOACAO DOA
        ON D.CD_DOADOR = DOA.CD_DOADOR
    GROUP BY  IC.NM_INSTITUICAO
        HAVING COUNT(DOA.CD_DOACAO) >=6
            ORDER BY COUNT(DOA.CD_DOACAO)  DESC


-- RECUPERANDO QUAL O DOADOR QUE MAIS RECICLOU
    SELECT D.NM_DOADOR,
           SUM(A.VL_PESO_MATERIAL) "TOTAL PESO RECICLAVEIS"
      FROM T_SRC_DOADOR D INNER JOIN T_SRC_DOACAO A
           ON(D.CD_DOADOR = A.CD_DOADOR)
     GROUP BY D.CD_DOADOR, D.NM_DOADOR
     ORDER BY "TOTAL PESO RECICLAVEIS" DESC;


-- RECUPERANDO QUAL O LIXO MAIS DOADO
    SELECT R.DS_TIPO,
           SUM(D.VL_PESO_MATERIAL) "TOTAL PESO RECICLAVEIS"
      FROM T_SRC_RECICLAVEL R  INNER JOIN T_SRC_DOACAO D
           ON(R.CD_RECICLAVEL = D.CD_RECICLAVEL)
     GROUP BY D.CD_RECICLAVEL, R.DS_TIPO
     ORDER BY "TOTAL PESO RECICLAVEIS" DESC;


-- RECUPERANDO QUAL DOADOR ARRECADOU MAIS DINHEIRO
    SELECT D.NM_DOADOR,
           SUM(A.VL_PESO_MATERIAL * R.VL_CASHBACK) "TOTAL CASHBACK ARRECADADO"
      FROM T_SRC_RECICLAVEL R INNER JOIN T_SRC_DOACAO A
           ON(R.CD_RECICLAVEL = A.CD_RECICLAVEL)
           INNER JOIN T_SRC_DOADOR D
           ON (D.CD_DOADOR = A.CD_DOADOR)
     GROUP BY A.CD_DOADOR, D.NM_DOADOR
     HAVING SUM(A.VL_PESO_MATERIAL * R.VL_CASHBACK) > 500
     ORDER BY "TOTAL CASHBACK ARRECADADO" DESC;


-- RECUPERANDO OS ESTADOS QUE TIVERAM MAIORES DOAÇÕES
    SELECT  L.NM_ESTADO,
        SUM(D.VL_PESO_MATERIAL) "TOTAL DE LIXO EM (KG)"
    FROM T_SRC_LOCALIZACAO L
        LEFT JOIN T_SRC_POSTO_COLETA C
        ON L.NR_CEP = C.NR_CEP
    LEFT JOIN T_SRC_DOACAO D
        ON C.CD_POSTO_COLETA = D.CD_POSTO_COLETA
            GROUP BY L.NM_ESTADO
        ORDER BY SUM(D.VL_PESO_MATERIAL) DESC
    fetch first 5 rows only



